# Contents
1. Import libraries
2. Import datasets
3. Creating a subset of the dataframe with a smaller number of rows
4. Checking the shape of the new subset
5. Grouping Data with Pandas
6. Performing a Single Aggregation
7. Using the mean function to retrieve the mean
8. Performing Multiple Aggregations
9. Aggregating Data with transform()
10. Deriving new columns (grouping variables) with loc()

# Import Libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Import the merged pickle dataset
ords_prods_merge = pd.read_pickle(r'C:\Users\TemporaryAdmin\Desktop\yoana_learning\Data Analytics\Immension\tasks\my_tasks\part_4\02_data\prepared_data\orders_products_merged_newvariables.pkl')

In [3]:
# Creating a subset of the dataframe with a smaller number of rows
df = ords_prods_merge[:1000000]

In [4]:
# Checking the new subset
df.head()

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,...,Unnamed: 0_y,product_name,aisle_id,department_id,prices,exists,price_range_loc,busiest_day,busiest_day_updated,busiest_period_of_day
0,0,0,2539329,1,prior,1,2,8,NaN,True,...,195.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy,fewest_orders
1,0,0,2539329,1,prior,1,2,8,NaN,True,...,14084.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy,fewest_orders
2,0,0,2539329,1,prior,1,2,8,NaN,True,...,12427.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy,fewest_orders
3,0,0,2539329,1,prior,1,2,8,NaN,True,...,26089.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy,fewest_orders
4,0,0,2539329,1,prior,1,2,8,NaN,True,...,26406.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy,fewest_orders

In [5]:
# Checking the shape of the new subset
df.shape

(1000000, 24)

# Grouping Data with Pandas

In [6]:
df.groupby('product_name')

In [7]:
# Performing a Single Aggregation- average number of orders per department ID
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              14.794925
2.0              17.085793
3.0              17.892742
4.0              17.880137
5.0              15.108513
6.0              15.352869
7.0              17.682741
8.0              16.496386
9.0              15.944846
10.0             20.104831
11.0             16.483104
12.0             15.614125
13.0             16.458631
14.0             17.523399
15.0             15.673392
16.0             18.012021
17.0             15.842139
18.0             19.349156
19.0             17.625805
20.0             17.113240
21.0             22.009038

In [8]:
# Using the mean function to retrieve the mean (instead of an agg function)
df.groupby('department_id')['order_number'].mean()

department_id
1.0     14.794925
2.0     17.085793
3.0     17.892742
4.0     17.880137
5.0     15.108513
6.0     15.352869
7.0     17.682741
8.0     16.496386
9.0     15.944846
10.0    20.104831
11.0    16.483104
12.0    15.614125
13.0    16.458631
14.0    17.523399
15.0    15.673392
16.0    18.012021
17.0    15.842139
18.0    19.349156
19.0    17.625805
20.0    17.113240
21.0    22.009038
Name: order_number, dtype: float64

In [9]:
# Performing Multiple Aggregations
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1.0              14.794925   1  99
2.0              17.085793   1  98
3.0              17.892742   1  99
4.0              17.880137   1  99
5.0              15.108513   1  99
6.0              15.352869   1  99
7.0              17.682741   1  99
8.0              16.496386   1  91
9.0              15.944846   1  99
10.0             20.104831   1  99
11.0             16.483104   1  99
12.0             15.614125   1  99
13.0             16.458631   1  99
14.0             17.523399   1  99
15.0             15.673392   1  99
16.0             18.012021   1  99
17.0             15.842139   1  99
18.0             19.349156   1  99
19.0             17.625805   1  99
20.0             17.113240   1  99
21.0             22.009038   1  97

# Aggregating Data with transform()

In [10]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [11]:
ords_prods_merge.head()

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,...,product_name,aisle_id,department_id,prices,exists,price_range_loc,busiest_day,busiest_day_updated,busiest_period_of_day,max_order
0,0,0,2539329,1,prior,1,2,8,NaN,True,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy,fewest_orders,11
1,0,0,2539329,1,prior,1,2,8,NaN,True,...,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy,fewest_orders,11
2,0,0,2539329,1,prior,1,2,8,NaN,True,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy,fewest_orders,11
3,0,0,2539329,1,prior,1,2,8,NaN,True,...,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy,fewest_orders,11
4,0,0,2539329,1,prior,1,2,8,NaN,True,...,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy,fewest_orders,11

In [12]:
pd.options.display.max_rows = None

In [13]:
ords_prods_merge.head(100)

,Unnamed: 0_x,Unnamed: 0.1,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,first_order,...,product_name,aisle_id,department_id,prices,exists,price_range_loc,busiest_day,busiest_day_updated,busiest_period_of_day,max_order
0,0,0,2539329,1,prior,1,2,8,NaN,True,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy,fewest_orders,11
1,0,0,2539329,1,prior,1,2,8,NaN,True,...,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy,fewest_orders,11
2,0,0,2539329,1,prior,1,2,8,NaN,True,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy,fewest_orders,11
3,0,0,2539329,1,prior,1,2,8,NaN,True,...,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy,fewest_orders,11
4,0,0,2539329,1,prior,1,2,8,NaN,True,...,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy,fewest_orders,11
5,1,1,2398795,1,prior,2,3,7,15.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Least busy,fewest_orders,11
6,1,1,2398795,1,prior,2,3,7,15.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Least busy,fewest_orders,11
7,1,1,2398795,1,prior,2,3,7,15.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Least busy,fewest_orders,11
8,1,1,2398795,1,prior,2,3,7,15.0,False,...,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,Least busy,fewest_orders,11
9,1,1,2398795,1,prior,2,3,7,15.0,False,...,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Least busy,fewest_orders,11
10,1,1,2398795,1,prior,2,3,7,15.0,False,...,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,Least busy,fewest_orders,11
11,2,2,473747,1,prior,3,3,12,21.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Least busy,fewest_orders,11
12,2,2,473747,1,prior,3,3,12,21.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Least busy,fewest_orders,11
13,2,2,473747,1,prior,3,3,12,21.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Least busy,fewest_orders,11
14,2,2,473747,1,prior,3,3,12,21.0,False,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Least busy,fewest_orders,11
15,2,2,473747,1,prior,3,3,12,21.0,False,...,Creamy Almond Butter,88.0,13.0,3.2,both,Low-range product,Regularly busy,Least busy,fewest_orders,11
16,3,3,2254736,1,prior,4,4,7,29.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,Least busy,fewest_orders,11
17,3,3,2254736,1,prior,4,4,7,29.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,Least busy,fewest_orders,11
18,3,3,2254736,1,prior,4,4,7,29.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,Least busy,fewest_orders,11
19,3,3,2254736,1,prior,4,4,7,29.0,False,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,Least busy,fewest_orders,11
20,3,3,2254736,1,prior,4,4,7,29.0,False,...,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Least busy,Least busy,fewest_orders,11
21,4,4,431534,1,prior,5,4,15,28.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,Least busy,fewest_orders,11
22,4,4,431534,1,prior,5,4,15,28.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,Least busy,fewest_orders,11
23,4,4,431534,1,prior,5,4,15,28.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,Least busy,fewest_orders,11
24,4,4,431534,1,prior,5,4,15,28.0,False,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,Least busy,fewest_orders,11
25,4,4,431534,1,prior,5,4,15,28.0,False,...,Organic Fuji Apples,24.0,4.0,2.7,both,Low-range product,Least busy,Least busy,fewest_orders,11
26,4,4,431534,1,prior,5,4,15,28.0,False,...,Honeycrisp Apples,24.0,4.0,14.0,both,Mid-range product,Least busy,Least busy,fewest_orders,11
27,4,4,431534,1,prior,5,4,15,28.0,False,...,Bartlett Pears,24.0,4.0,5.0,both,Low-range product,Least busy,Least busy,fewest_orders,11
28,4,4,431534,1,prior,5,4,15,28.0,False,...,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Least busy,Least busy,fewest_orders,11
29,5,5,3367565,1,prior,6,2,7,19.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy,fewest_orders,11
30,5,5,3367565,1,prior,6,2,7,19.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy,fewest_orders,11
31,5,5,3367565,1,prior,6,2,7,19.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Regularly busy,fewest_orders,11
32,5,5,3367565,1,prior,6,2,7,19.0,False,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Regularly busy,fewest_orders,11
33,6,6,550135,1,prior,7,1,9,20.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest day,fewest_orders,11
34,6,6,550135,1,prior,7,1,9,20.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest day,fewest_orders,11
35,6,6,550135,1,prior,7,1,9,20.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest day,fewest_orders,11
36,6,6,550135,1,prior,7,1,9,20.0,False,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest day,fewest_orders,11
37,6,6,550135,1,prior,7,1,9,20.0,False,...,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,Busiest day,fewest_orders,11
38,7,7,3108588,1,prior,8,1,14,14.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest day,most_orders,11
39,7,7,3108588,1,prior,8,1,14,14.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest day,most_orders,11
40,7,7,3108588,1,prior,8,1,14,14.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest day,most_orders,11
41,7,7,3108588,1,prior,8,1,14,14.0,False,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest day,most_orders,11
42,7,7,3108588,1,prior,8,1,14,14.0,False,...,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Regularly busy,Busiest day,most_orders,11
43,7,7,3108588,1,prior,8,1,14,14.0,False,...,Organic Half & Half,53.0,16.0,1.8,both,Low-range product,Regularly busy,Busiest day,most_orders,11
44,8,8,2295261,1,prior,9,1,16,0.0,False,...,Organic Half & Half,53.0,16.0,1.8,both,Low-range product,Regularly busy,Busiest day,fewest_orders,11
45,8,8,2295261,1,prior,9,1,16,0.0,False,...,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Regularly busy,Busiest day,fewest_orders,11
46,8,8,2295261,1,prior,9,1,16,0.0,False,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest day,fewest_orders,11
47,8,8,2295261,1,prior,9,1,16,0.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest day,fewest_orders,11
48,8,8,2295261,1,prior,9,1,16,0.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest day,fewest_orders,11
49,8,8,2295261,1,prior,9,1,16,0.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest day,fewest_orders,11
50,9,9,2550362,1,prior,10,4,8,30.0,False,...,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,Least busy,fewest_orders,11
51,9,9,2550362,1,prior,10,4,8,30.0,False,...,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Least busy,Least busy,fewest_orders,11
52,9,9,2550362,1,prior,10,4,8,30.0,False,...,Milk Chocolate Almonds,45.0,19.0,6.8,both,Mid-range product,Least busy,Least busy,fewest_orders,11
53,9,9,2550362,1,prior,10,4,8,30.0,False,...,0% Greek Strained Yogurt,120.0,16.0,12.6,both,Mid-range product,Least busy,Least busy,fewest_orders,11
54,9,9,2550362,1,prior,10,4,8,30.0,False,...,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,Least busy,fewest_orders,11
55,9,9,2550362,1,prior,10,4,8,30.0,False,...,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,Least busy,fewest_orders,11
56,9,9,2550362,1,prior,10,4,8,30.0,False,...,Organic Unsweetened Almond Milk,91.0,16.0,1.3,both,Low-range product,Least busy,Least busy,fewest_orders,11
57,9,9,2550362,1,prior,10,4,8,30.0,False,...,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Least busy,Least busy,fewest_orders,11
58,9,9,2550362,1,prior,10,4,8,30.0,False,...,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,Least busy,fewest_orders,11
59,10,10,1187899,1,train,11,4,8,14.0,False,...,NaN,NaN,NaN,NaN,left_only,NaN,Least busy,Least busy,fewest_orders,11
60,11,11,2168274,2,prior,1,2,11,NaN,True,...,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
61,11,11,2168274,2,prior,1,2,11,NaN,True,...,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
62,11,11,2168274,2,prior,1,2,11,NaN,True,...,Roasted Turkey,96.0,20.0,2.3,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
63,11,11,2168274,2,prior,1,2,11,NaN,True,...,Baked Organic Sea Salt Crunchy Pea Snack,72.0,13.0,10.9,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
64,11,11,2168274,2,prior,1,2,11,NaN,True,...,Thin Stackers Brown Rice Lightly Salted,78.0,19.0,2.7,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
65,11,11,2168274,2,prior,1,2,11,NaN,True,...,Cheddar Bunnies Snack Crackers,78.0,19.0,4.1,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
66,11,11,2168274,2,prior,1,2,11,NaN,True,...,Plantain Chips,107.0,19.0,5.0,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
67,11,11,2168274,2,prior,1,2,11,NaN,True,...,Organic Just Concord Grape Juice,98.0,7.0,9.4,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
68,11,11,2168274,2,prior,1,2,11,NaN,True,...,Uncured Genoa Salami,96.0,20.0,14.8,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
69,11,11,2168274,2,prior,1,2,11,NaN,True,...,Original Hummus,67.0,20.0,7.5,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
70,11,11,2168274,2,prior,1,2,11,NaN,True,...,Organic Raspberries,123.0,4.0,4.4,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
71,11,11,2168274,2,prior,1,2,11,NaN,True,...,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
72,11,11,2168274,2,prior,1,2,11,NaN,True,...,Honeycrisp Apple,24.0,4.0,2.5,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
73,12,12,1501582,2,prior,2,5,10,10.0,False,...,Strawberries,24.0,4.0,1.3,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
74,12,12,1501582,2,prior,2,5,10,10.0,False,...,Goat Cheese Log,21.0,16.0,2.0,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
75,12,12,1501582,2,prior,2,5,10,10.0,False,...,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
76,12,12,1501582,2,prior,2,5,10,10.0,False,...,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
77,12,12,1501582,2,prior,2,5,10,10.0,False,...,"Pita Chips, Simply Naked, Party Size",107.0,19.0,3.9,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
78,12,12,1501582,2,prior,2,5,10,10.0,False,...,Traditional Hummus,67.0,20.0,2.0,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
79,13,13,1901567,2,prior,3,1,10,3.0,False,...,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,Busiest day,most_orders,15
80,13,13,1901567,2,prior,3,1,10,3.0,False,...,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,Busiest day,most_orders,15
81,13,13,1901567,2,prior,3,1,10,3.0,False,...,Roasted Turkey,96.0,20.0,2.3,both,Low-range product,Regularly busy,Busiest day,most_orders,15
82,13,13,1901567,2,prior,3,1,10,3.0,False,...,Organic Sticks Low Moisture Part Skim Mozzarel...,21.0,16.0,6.6,both,Mid-range product,Regularly busy,Busiest day,most_orders,15
83,13,13,1901567,2,prior,3,1,10,3.0,False,...,Carrot Ginger Soup,1.0,20.0,6.2,both,Mid-range product,Regularly busy,Busiest day,most_orders,15
84,14,14,738281,2,prior,4,2,10,8.0,False,...,Artichoke Spinach Dip,67.0,20.0,7.1,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
85,14,14,738281,2,prior,4,2,10,8.0,False,...,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
86,14,14,738281,2,prior,4,2,10,8.0,False,...,Hommus Classic Original,67.0,20.0,7.5,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
87,14,14,738281,2,prior,4,2,10,8.0,False,...,Good Belly Probiotics Juice Drink Blueberry Ac...,31.0,7.0,5.8,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
88,14,14,738281,2,prior,4,2,10,8.0,False,...,Organic Roasted Sliced Chicken Breast,96.0,20.0,8.9,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
89,14,14,738281,2,prior,4,2,10,8.0,False,...,Organic Gala Apples,24.0,4.0,9.1,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
90,14,14,738281,2,prior,4,2,10,8.0,False,...,Multigrain Flax Seeded Flatbread Crackers,78.0,19.0,5.5,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
91,14,14,738281,2,prior,4,2,10,8.0,False,...,Banana,24.0,4.0,12.3,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
92,14,14,738281,2,prior,4,2,10,8.0,False,...,Organic Hass Avocado,24.0,4.0,4.0,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
93,14,14,738281,2,prior,4,2,10,8.0,False,...,Kalamata Olive Spread,67.0,20.0,10.8,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
94,14,14,738281,2,prior,4,2,10,8.0,False,...,Pad Thai,38.0,1.0,12.6,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
95,14,14,738281,2,prior,4,2,10,8.0,False,...,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,both,Low-range product,Regularly busy,Regularly busy,most_orders,15
96,14,14,738281,2,prior,4,2,10,8.0,False,...,Fire Grilled Steak Bowl,38.0,1.0,5.9,both,Mid-range product,Regularly busy,Regularly busy,most_orders,15
97,15,15,1673511,2,prior,5,3,11,8.0,False,...,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,both,Mid-range product,Regularly busy,Least busy,most_orders,15
98,15,15,1673511,2,prior,5,3,11,8.0,False,...,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,both,Low-range product,Regularly busy,Least busy,most_orders,15
99,15,15,1673511,2,prior,5,3,11,8.0,False,...,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,both,Low-range product,Regularly busy,Least busy,most_orders,15

# Deriving Columns with loc()

In [14]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [15]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [16]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [17]:
ords_prods_merge['loyalty_flag'].value_counts(dropna= False)

Regular customer    16381472
Loyal customer      10679578
New customer         5580218
Name: loyalty_flag, dtype: int64

In [19]:
ords_prods_merge['loyalty_flag'].head(10)

0    Regular customer
1    Regular customer
2    Regular customer
3    Regular customer
4    Regular customer
5    Regular customer
6    Regular customer
7    Regular customer
8    Regular customer
9    Regular customer
Name: loyalty_flag, dtype: object

In [20]:
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(10)

   user_id      loyalty_flag  order_number
0        1  Regular customer             1
1        1  Regular customer             1
2        1  Regular customer             1
3        1  Regular customer             1
4        1  Regular customer             1
5        1  Regular customer             2
6        1  Regular customer             2
7        1  Regular customer             2
8        1  Regular customer             2
9        1  Regular customer             2